name: "Basic Tests"
on:
  pull_request:
  push:
jobs:
  nix-instantiate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: nix-instantiate ./release.nix --option allow-import-from-derivation false --show-trace
  generate-keys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: nix-build ./release.nix -A testGenerateKeys --show-trace
  nixos-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm
    - uses: cachix/cachix-action@v8
      with:
        name: robotnix
    - run: nix-build ./release.nix -A tests.attestation-server
  flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: |
        nix flake check
        export ORIG_DIR=$PWD
        cd $(mktemp -d)
        nix flake init -t $ORIG_DIR
        nix flake check --override-input robotnix $ORIG_DIR
